name: $(Date:yyyyMMdd)$(Rev:.r)

trigger:
  batch: true
  branches:
    include:
      - main
pr: none

resources:
  repositories:
    - repository: templates
      type: github
      name: microsoft/vscode-engineering
      ref: main
      endpoint: Monaco

parameters:
  - name: publishPackage
    displayName: 🚀 Publish native-watchdog
    type: boolean
    default: false

extends:
  template: azure-pipelines/npm-package/pipeline.yml@templates
  parameters:
    npmPackages:
      - name: native-watchdog

        buildSteps:
          - script: npm ci
            displayName: Install dependencies

        testPlatforms:
          - name: Linux
            nodeVersions:
              - 22.x
          - name: MacOS
            nodeVersions:
              - 22.x
          - name: Windows
            nodeVersions:
              - 22.x

        testSteps:
          - script: npm ci
            displayName: Install dependencies

          - script: npm test
            displayName: Test

        apiScanSoftwareName: "vscode-native-watchdog"
        apiScanSoftwareVersion: "1.4"

        publishPackage: ${{ parameters.publishPackage }}
